export const authConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOAD_REQUEST: "USER_LOAD_REQUEST",
  USER_LOAD_SUCCESS: "USER_LOAD_SUCCESS",
  AUTH_ERROR: "AUTH_ERROR",
  USER_LOGOUT: "USER_LOGOUT",
};
